name: Build Linux Server

on: [push, workflow_dispatch]

jobs:
  build:
    name: Build and Run Tests

    strategy:
      matrix:
        unityVersion:
          - 2023.2.9f1
          # - 2023.1.20f1
          # - 2022.3.19f1
          # - 2021.3.34f1
        os:
          - ubuntu-latest
          # - windows-latest
    
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Cache
        uses: actions/cache@v3
        with:
          path: ${{ matrix.projectPath }}/Library
          key:
            Library-${{ matrix.projectPath }}-${{ matrix.targetPlatform }}-${{ hashFiles(matrix.projectPath) }}
          restore-keys: |
            Library-${{ matrix.projectPath }}-${{ matrix.targetPlatform }}-
            Library-${{ matrix.projectPath }}-
            Library-


      - name: Build ACSSandbox Server
        uses: game-ci/unity-builder@v4
        env:
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
        with:
          projectPath: ACSSandbox.Unity
          buildMethod: ACSSandbox.ACSSandboxBuild.BuildServer
          unityVersion: ${{ matrix.unityVersion }}
          targetPlatform: StandaloneLinux64

      # # Test
      # - name: run tests
      #   uses: game-ci/unity-test-runner@v4
      #   env:
      #     UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
      #     UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
      #     UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
      #   with:
      #     packageMode: true
      #     unityVersion: ${{ matrix.unityVersion }}
      #     githubToken: ${{ secrets.GITHUB_TOKEN }}