name: Actions

on: [push, workflow_dispatch]

jobs:
  build:
    name: For testing purposes
    
    strategy:
      matrix:
        unityVersion:
          - 2023.2.7f1
          - 2023.1.20f1
          - 2022.3.19f1
          - 2021.3.34f1
        os:
          - ubuntu-latest
          # - windows-latest
        projectPath:
          - ACSSandbox.Unity
    
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Cache
        uses: actions/cache@v3
        with:
          path: ${{ matrix.projectPath }}/Library
          key:
            Library-${{ matrix.projectPath }}-${{ matrix.targetPlatform }}-${{ hashFiles(matrix.projectPath) }}
          restore-keys: |
            Library-${{ matrix.projectPath }}-${{ matrix.targetPlatform }}-
            Library-${{ matrix.projectPath }}-
            Library-

      - name: Build server
        uses: game-ci/unity-builder@v4
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
        with:
          projectPath: ${{ matrix.projectPath }}
          targetPlatform: StandaloneLinux64